### ISSUE TITLE
Size Class Configuration File Support

### ISSUE THREAD

**Issue by kohlmannj** [nytpi/nytpi-sass-utils#4]
In theory it should be possible to support completely customizable size classes. Here's an example of what a JSON-based configuration file might look like:

```json
"classes": {
	"mobile-portrait": {
		"width": 640,
		"grid": "4 0.25",
		"rangeX": "to 958"
	},
	"tablet-portrait": {
		"width": 1536,
		"grid": "6 0.25",
		"rangeX": "from 960 to 1706"
	},
	"tablet-landscape": {
		"width": 2048,
		"grid": "8 0.25",
		"rangeX": "from 1708 to 2558"
	},
	"desktop": {
		"width": 2560,
		"grid": "12 0.25",
		"rangeX": "from 2560"
	},
	"mobile-landscape": {
		"width": 1136,
		"grid": "4 0.25",
		"rangeY": "to 1136",
		"media": "(orientation: landscape)"
	}
},

"families": {
	"compact": "mobile-portrait",
	"regular": "desktop to tablet-portrait",
	"all-mobile": "mobile-portrait to desktop",
	"all-desktop": "desktop to mobile-portrait",
	
	"tablet": "tablet-portrait to tablet-landscape",
	"all-tablet": "tablet-portrait from mobile-portrait to desktop",
	"tablet": "tablet-portrait for mobile-landscape, tablet-portrait to tablet-landscape",
	
	"all-desktop-improved": "desktop for mobile-landscape, tablet-portrait to desktop",
	"regular-order-insensitive": "desktop for tablet-portrait to desktop",
	"all-desktop-order-insensitive": "desktop for mobile-portrait to desktop"
}
```

To do items:

- Determine if arrays of integers are better or worse for `"range*"` properties than the string format shown above
- Review Susy's media query and layout map implementations and see if there's an opportunity to model or extend either of those in some way with this configuration format
- Determine if Size Classes should even be concerned with vertical coordinates (as alluded to with the `mobile-landscape` size class above)
- Suggest a format for Size Class breakpoints, which are conceptually subordinate to a single size class

**Comment by powersimple** [comment]
Nice Work Joe!

**Comment by kohlmannj** [comment]
Another issue to consider: how much more work is required to support overlapping size classes? One important design consideration of the current system is that all four size classes are non-overlapping (i.e. disjoint). This means they can be simply and reliably "merged", among other things.

**Comment by kohlmannj** [comment]
This has been implemented in the development branch of nytpi-sass-utils. The current config JSON file looks like this: https://github.com/nytpi/nytpi-sass-utils/blob/development/sass/size-class-v3/nytpi-default.json

There are several behind-the-scenes pieces going on to successfully implement this. [This Eyeglass-based JavaScript code](https://github.com/nytpi/nytpi-sass-utils/blob/development/eyeglass-exports.js#L160) shows how the JSON config file is getting imported and selectively converting some values to Sass Number objects, since [node-sass-utils](https://github.com/sass-eyeglass/node-sass-utils)' conversion from JS object to Sass map doesn't do this for us.

**Comment by kohlmannj** [comment]
Also, it's possible to specify your own JSON-based config file and (by default) merge it into the default config:

_In js/size-class-config.json…_
```json
{
  "families": {
    "desktop-and-tablet-local-config": "desktop from desktop to tablet-landscape",
    "regular-pixels": "desktop for desktop to tablet-portrait with pixel-grid",
    "regular-grid": "desktop grid for desktop to tablet-portrait",
    "all-mobile-pixels": "mobile-portrait to desktop with pixel-grid",
    "all-desktop-pixels": "pixel-grid for desktop to mobile-portrait",
    "weird-family": "pixel-grid desktop to mobile-portrait",
    "also-weird-family": "tablet-portrait to tablet-landscape pixel-grid",
    "tiny-tablet": "tablet-portrait for 0 to 480px",
    "big-tablet": "tablet-portrait for 1024px",
    "forever-tablet-landscape": "tablet-landscape for 0",
    "desktop-for-tablet": "desktop for tablet-portrait"
  }
}
```

_In scss/main.scss…_
```scss
@import "nytpi-sass-utils/size-class-v3";
@include get-size-class-config("../js/size-class-config.json");
```

**Comment by kohlmannj** [comment]
This configuration support is mostly complete in the development branch. For future enhancements, please refer to #7.
